# Generated by Django 3.2.14 on 2022-07-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='users',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_log',
            new_name='date_logged',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
