global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.


# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  #- "alert.rules"
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: "monitoring"
    
    static_configs:
      #- targets:
        #- host.docker.internal
      - targets: ["localhost:9090"]
      #- targets: ["host.docker.internal:8000"]
      #- targets: ["localhost:8000"]
      #- targets: ["133.186.143.213:9090"]

  - job_name: "django"
    static_configs:
      #- targets:
        #- host.docker.internal
      - targets: ["backend:8000"]
  - job_name: "node-exporter"

    static_configs:
      - targets: ["node-exporter:9100"]
