# Generated by Django 3.2.14 on 2022-07-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='fish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_id', to='images.fish_info'),
        ),
    ]
