# Generated by Django 3.2.14 on 2022-07-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testField', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
