# Generated by Django 3.2.14 on 2022-07-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_rename_fish_info_fish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='url',
        ),
    ]
